kind: Service
apiVersion: v1
metadata:
  name: keycloak-nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: true
spec:
  type: LoadBalancer
  selector:
    workloadID_keycloak: "true"
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31001
    name: http
    protocol: TCP
  - port: 8443
    targetPort: 8443
    nodePort: 31002
    name: https
    protocol: TCP
  externalTrafficPolicy: Cluster

