kind: Service
apiVersion: v1
metadata:
  name: keycloak-nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: true
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
  - port: 8443
    targetPort: 8443
    name: https
    protocol: TCP
  externalTrafficPolicy: Cluster

